name: Build Android APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev xclip libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev make fontconfig libjpeg-dev autoconf automake libtool pkg-config zlib1g-dev python3-pip python3-setuptools
        pip install --user --upgrade buildozer cython virtualenv
        pip install python-for-android

    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug --no-clean

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Keep-Secret-VIP-APK
        path: bin/*.apk
